# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 268a3db373f8d7accd2c4602c80ca4db958403971c98f7cb6b3d504971ca97f1959190f3c5e984bd3cbcf5316d93cf7d6e950444cb5caa582a067a0e7edf3e67

test:
  secret_key_base: f5d271ee8b531b473b5c576958d68c41a388b9d15f03b87c498c8aa40f4e6942bf6db86232683e2d016333ef8712feca8ea9af328b54188428fc65e50a3ff400

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>